apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend-deployment
        image: achoistic98/ccs_backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: database-service:3306
        - name: ORIGIN
          value: frontend-service:3000
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "chatdb"
        - name: DB_USER
          value: "root"
        - name: FILE_LOCATION
          value: "localhost:8080/assets"